### ISSUE TITLE
502 Bad Gateway at staging 

### ISSUE THREAD

**Issue by matkoniecz** [colouring-cities/colouring-london#973]
https://cl-staging.uksouth.cloudapp.azure.com/view/planning

@tomalrussell @mdsimpson42 Can you look into Azure console is there any indicator of things going wrong way? (I do not have an access to Azure console)

`pm2 logs` are not showing problems when connected

rebooting server with `sudo reboot` worked for few minutes, then problem started again

---------------

now I see

```
/home/cladmin/.pm2/logs/colouringlondon-error-0.log last 15 lines:
0|colourin | Error: Input Buffer is empty
0|colourin |     at Sharp._createInputDescriptor (/var/www/colouring-london/app/node_modules/sharp/lib/input.js:34:13)
0|colourin |     at /var/www/colouring-london/app/node_modules/sharp/lib/composite.js:107:19
0|colourin |     at Array.map (<anonymous>)
0|colourin |     at Sharp.composite (/var/www/colouring-london/app/node_modules/sharp/lib/composite.js:101:35)
0|colourin |     at im (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/stitchTile.ts:21:8)
0|colourin |     at im (/var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/renderers/getTileWithCaching.ts:7:15)
0|colourin |     at /var/www/colouring-london/app/build/webpack:/colouring-london-app/src/tiles/tileserver.ts:20:15
```

in logs

**Comment by matkoniecz** [comment]
problem disappeared, hopefully forever
